Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7"

  config.vm.synced_folder "./bin", "/vagrant/bin"

  config.vm.provision "shell", inline: <<-SHELL
    chmod +x /vagrant/bin/go-ipset-test
    sudo /vagrant/bin/go-ipset-test
  SHELL
end
