#!/bin/sh

set -e

DOCKER_IMAGE_NAME="go-ipset-build"
DOCKER_CONTAINER_NAME="go-ipset-build-container"

if [[ $(docker ps -a | grep $DOCKER_CONTAINER_NAME) != "" ]]; then
  docker rm -f $DOCKER_CONTAINER_NAME 2>/dev/null
fi

docker build -t $DOCKER_IMAGE_NAME .

docker run --name $DOCKER_CONTAINER_NAME \
  $DOCKER_IMAGE_NAME \
  make "$@"
